### ISSUE TITLE
Use of Bayer8 source files 

### ISSUE THREAD

**Issue by checor** [hgrecco/pixelinkds#1]
Hello, first of all, congrats on your work! It was exactly I was looking for, a quick way to convert a .pds file to a video format.

I've tried use your library with a BAYER8_RGGB stream, since it's the only type my camera captures. I wanted to convert it to .avi, and gives me a warning about not fully supported, and the crashes:

```
C:\Python36-32>python.exe -m pixelinkds convert "C:\Users\User\Desktop\1.pds" myfile.avi
C:\Python36-32\lib\site-packages\pixelinkds\reader.py:91: UserWarning: PixelFormat.BAYER8_RGGB is not currently supported by the Reader.
Raw data will be returned
  'Raw data will be returned' % fmt)
Traceback (most recent call last):
  File "C:\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-32\lib\site-packages\pixelinkds\__main__.py", line 47, in <module>
    convert(args.input, args.output)
  File "C:\Python36-32\lib\site-packages\pixelinkds\__init__.py", line 64, in convert
    func(r, output)
  File "C:\Python36-32\lib\site-packages\pixelinkds\converters.py", line 62, in save_avi
    for t, img in reader:
  File "C:\Python36-32\lib\site-packages\pixelinkds\reader.py", line 163, in __iter__
    desc, img = self.next()
  File "C:\Python36-32\lib\site-packages\pixelinkds\reader.py", line 179, in next
    self._fin_read_many(self._read_dtype1, self._read_count).reshape(self._read_shape))
ValueError: cannot reshape array of size 34865152 into shape (4980736,1)
```

I would be happy to have a .avi in Bayer format if it's posible, since I will manipulate with OpenCV the images afterwards. But I can't convert to any format with sucess. I think it wouldn't be hard to support Bayer if the user already has OpenCV, it's only a `cvtColor` call.

Do you think that the file being Bayer it's the source of the crash? I can help you coding or testing if you want.

Thanks!

**Comment by checor** [comment]
Hello again,

I would like to work on this issue. But, I want to know if this project it's still active, so it can be part of the codebase.

Please let me know if you are interested.

Thanks!

**Comment by hgrecco** [comment]
Yes! I will be happy to merge a PR with this. Go for it!
